config/routes.rb
Bookstore::Application.routes.draw do

  resources :sales do
    resources :sale_items
  end

  resources :books

  devise_for :users

  root :to => "books#index"
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :description, :name, :release_date, :photo, :price

  has_attached_file :photo

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :amount, :status, :user_id

  has_many :sale_items

  before_create :default_status

  def default_status
    self.status = "pending"
  end
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
  attr_accessible :book_id, :sale_id

  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :is_admin
  # attr_accessible :title, :body

  has_many :sales
  has_one :active_sale, :class_name => "Sale", :conditions => {:status => "pending"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :admin_only!, :except => [:index, :show]
  # GET /books
  # GET /books.json
  def index
    redirect_to new_user_session_path and return unless current_user
    @books = Book.all
    @sale = current_user.active_sale || current_user.sales.create

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
  def admin_only!
    unless current_user and current_user.is_admin?
      redirect_to root_path, :flash => {:error => "You need permission to update assets."}
    end
  end
end

app/controllers/sale_items_controller.rb
class SaleItemsController < ApplicationController
  before_filter :authenticate_user!
  # GET /sale_items
  # GET /sale_items.json
  def index
    @sale_items = SaleItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sale_items }
    end
  end

  # GET /sale_items/1
  # GET /sale_items/1.json
  def show
    @sale_item = SaleItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale_item }
    end
  end

  # GET /sale_items/new
  # GET /sale_items/new.json
  def new
    @sale_item = SaleItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sale_item }
    end
  end

  # GET /sale_items/1/edit
  def edit
    @sale_item = SaleItem.find(params[:id])
  end

  # POST /sale_items
  # POST /sale_items.json
  def create
    @sale = Sale.find(params[:sale_id])
    @sale_item = @sale.sale_items.new(:book_id => params[:book_id])

    respond_to do |format|
      if @sale_item.save
        format.html { redirect_to root_path, notice: 'Sale item was successfully created.' }
        format.json { render json: @sale_item, status: :created, location: @sale_item }
      else
        format.html { redirect_to :back }
        format.json { render json: @sale_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sale_items/1
  # PUT /sale_items/1.json
  def update
    @sale_item = SaleItem.find(params[:id])

    respond_to do |format|
      if @sale_item.update_attributes(params[:sale_item])
        format.html { redirect_to @sale_item, notice: 'Sale item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_items/1
  # DELETE /sale_items/1.json
  def destroy
    @sale_item = SaleItem.find(params[:id])
    @sale_item.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_filter :authenticate_user!
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale = Sale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render json: @sale, status: :created, location: @sale }
      else
        format.html { render action: "new" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br />
    <%= f.date_select :release_date %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

<table style="float: left;">
<% @books.each_slice(3) do |books| %>
  <tr>
    <% books.each do |book| %>
      <td width="200" style="width:200px;padding: 10px;">
        <%= image_tag book.photo, :size => "200x300" %> <br>
        <%= book.name %> <br>
        <%= book.author %> <br>
        <%= book.release_date %> <br>
        <p style="text-align: left;"><%= book.description %> </p><br>
        HK$ <%= book.price %><br>
        <%= @sale.sale_items.map(&:book).include?(book) ? "In your basket now" :
                    (link_to "Add to basket", sale_sale_items_path(@sale, :book_id => book), :method => :post) %> <br>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

<div style="width:280px;float:right">
  <%= render "sales/basket" %>
</div>

<br />

<%= link_to 'New Book', new_book_path if current_user.is_admin?%>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @book.name %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Release date:</b>
  <%= @book.release_date %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%#= stylesheet_link_tag    "application", :media => "all" %>
  <%#= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="text-align: center;">
  <div style="margin:auto;width:960px;text-align: left;">
    <%= yield %>
  </div>
</body>
</html>

app/views/sale_items/_form.html.erb
<%= form_for(@sale_item) do |f| %>
  <% if @sale_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale_item.errors.count, "error") %> prohibited this sale_item from being saved:</h2>

      <ul>
      <% @sale_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sale_id %><br />
    <%= f.number_field :sale_id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.number_field :book_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sale_items/edit.html.erb
<h1>Editing sale_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale_item %> |
<%= link_to 'Back', sale_items_path %>

app/views/sale_items/index.html.erb
<h1>Listing sale_items</h1>

<table>
  <tr>
    <th>Sale</th>
    <th>Book</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sale_items.each do |sale_item| %>
  <tr>
    <td><%= sale_item.sale_id %></td>
    <td><%= sale_item.book_id %></td>
    <td><%= link_to 'Show', sale_item %></td>
    <td><%= link_to 'Edit', edit_sale_item_path(sale_item) %></td>
    <td><%= link_to 'Destroy', sale_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sale item', new_sale_item_path %>

app/views/sale_items/new.html.erb
<h1>New sale_item</h1>

<%= render 'form' %>

<%= link_to 'Back', sale_items_path %>

app/views/sale_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sale:</b>
  <%= @sale_item.sale_id %>
</p>

<p>
  <b>Book:</b>
  <%= @sale_item.book_id %>
</p>


<%= link_to 'Edit', edit_sale_item_path(@sale_item) %> |
<%= link_to 'Back', sale_items_path %>

app/views/sales/_basket.html.erb
<% if @sale.sale_items.empty? %>
    Your basket is empty? Add any books from left
<% else %>
  Your reading list:
  <table>
    <% @sale.sale_items.each do |item| %>
      <tr>
        <td><%= image_tag item.book.photo, :size=>"40x60" %></td>
        <td><%= item.book.name.first(10) %></td>
        <td>HK$ <%= item.book.price %></td>
        <td><%= link_to image_tag("trash.png", :size => "20x20"), sale_sale_item_path(@sale, item), :method => :delete %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Listing sales</h1>

<table>
  <tr>
    <th>User</th>
    <th>Amount</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sales.each do |sale| %>
  <tr>
    <td><%= sale.user_id %></td>
    <td><%= sale.amount %></td>
    <td><%= sale.status %></td>
    <td><%= link_to 'Show', sale %></td>
    <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
    <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @sale.user_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @sale.amount %>
</p>

<p>
  <b>Status:</b>
  <%= @sale.status %>
</p>


<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>